# Generated by Django 3.2.16 on 2022-10-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('salary_per_hour', models.IntegerField()),
                ('working_hours', models.IntegerField()),
                ('total_salary', models.IntegerField()),
            ],
        ),
    ]
